email: contact@shyaman.me
cv: https://drive.google.com/file/d/1UJJgbMi6DRAnnUzyjwFrOX_zkd7uT-GT/view?usp=sharing
linkedin: https://www.linkedin.com/in/shyaman-jayasundara
orcid: https://orcid.org/0000-0003-0522-3353
flickr: https://www.flickr.com/photos/shyaman321
github: https://github.com/shyaman/
facebook: https://www.github.com/shyaman/
twitter: https://twitter.com/shyaman_madhawa
instagram: https://www.instagram.com/__shyaman__/
pinterest: https://www.pinterest.com/shyaman_j/
youtube: https://www.youtube.com/channel/UChoPlHOdGXodB_2D2yNOf2w
currentTitle: B.Sc. Eng (Hons), AMIESL | Research assistant <a
  href="http://agri.pdn.ac.lk/agbc/" target="_blank">AgBC</a> | Co-Founder <a
  href="https://www.fixyinnovations.com" target="_blank"> Fixy Innovations</a>
bio: I am a data science enthusiastic who is having interests in Bioinformatics
  and Biomedical informatics. Apart from that, I love traveling and capturing
  memorable moments with my loved ones.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
timezone: Asia/Colombo
url: https://www.shyaman.me
defaults:
  - scope:
      path: admin/**
    values:
      sitemap: false
repository: shyaman/shyaman.github.io
