email: contact@shyaman.me
cv: https://drive.google.com/file/d/1UJJgbMi6DRAnnUzyjwFrOX_zkd7uT-GT/view?usp=sharing
linkedin: https://www.linkedin.com/in/shyaman-jayasundara
orcid: https://orcid.org/0000-0003-0522-3353
youtube: https://www.youtube.com/channel/UChoPlHOdGXodB_2D2yNOf2w
flickr: https://www.flickr.com/photos/shyaman321
github: https://github.com/shyaman/
updateddate: 05/08/2021