plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
linkedin: https://www.linkedin.com/in/shyaman-jayasundara
flickr: https://www.flickr.com/photos/shyaman321
github: https://github.com/shyaman/
facebook: https://www.facebook.com/shyaman.madhawa/
youtube: https://www.youtube.com/channel/UChoPlHOdGXodB_2D2yNOf2w
currentTitle: PhD Student (Computer Science) and Graduate Research Assistant |
  B.Sc. Eng (Hons), AMIESL
bio: I am a data science enthusiastic who is having interests in Bioinformatics
  and Biomedical informatics. Apart from that, I love traveling and capturing
  memorable moments with my loved ones.
repository: shyaman/shyaman.github.io
url: https://www.shyaman.me
defaults:
  - scope:
      path: admin/**
    values:
      sitemap: false
cv: https://drive.google.com/file/d/1UJJgbMi6DRAnnUzyjwFrOX_zkd7uT-GT/view?usp=sharing
twitter: https://twitter.com/shyaman_madhawa
instagram: https://www.instagram.com/shyaman_j/
timezone: Asia/Colombo
email: contact@shyaman.me
orcid: https://orcid.org/0000-0003-0522-3353
pinterest: https://www.pinterest.com/shyaman_j/
