backend:
  name: github
  repo: shyaman/shyaman.github.io # Path to your GitHub repository
  branch: dev # Branch to update (optional; defaults to master

media_folder: "assets/img" # Media files will be stored in the repo under images/uploads

collections:
- label: "Main site contents"
  name: content
  editor:
    preview: false
  files:
    - label: "Education"
      name: edu
      file: "_data/education.yml"
      fields:
        - label: "Entries"
          label_singular: "Entry"
          name: eduEntry
          widget: list
          fields:
            - {label: VenueS, name: venue, widget: string}
            - {label: Achievement, name: achievement, widget: string}
            - {label: Description, name: description, widget: string}
            - {label: Duration, name: duration, widget: string}
